apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: flaskapi
  labels:
    app: flaskapi-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskapi-1
  serviceName: flask-statefulset-frontend
  template:
    metadata:
      labels:
        app: flaskapi-1
    spec:
      initContainers:
        - name: init-db
          image: busybox:1.31
          command: ['sh', '-c', "until nslookup mysql.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mysql; sleep 2; done"]
          #command: ['sh', '-c', 'echo -e "Checking for the availability of MySQL Server deployment"; while ! nc -z mysql 3306; do sleep 1; printf "-"; done; echo -e "  >> MySQL DB Server has started";']


      containers:
        - name: flaskapi-container
          image: klogambigai/pythonweb:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: "REDIS_HOST"
              value: "redis-master"
            - name: DB_HOSTNAME
              value: "mysql"
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: "guestapp"
            - name: DB_USERNAME
              value: "root"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-db
                  key: password
