web:
  build: .
  ports:
    - "8000:8000"
  links:
    - mysql:mysql
    - redis:redis
  env_file: .env
  #command: /code/manage.py runserver 0.0.0.0:8000

mysql:
  build: .
  ports
  environment:
    - MYSQL_DATABASE=mysql
    - MYSQL_ROOT_PASSWORD=admin123
  ports:
    - "3306:3306"
  volumes:
    - data-volume:/var/lib/mysql
redis:
  image: redis:latest
  ports:
    - "6379:6379"

