version: '3.8'

services:
 web:
  build:
   context: ./app
  ports:
  - 8000:8000
  links:
  - mysqldb
  environment:
  - FLASK_ENV: development
  volumes:
  - ./:/app

 mysqldb:
  build:
   context: ./db
  ports:
  - 3306:3306
  environment:
  - MYSQL_ROOT_PASSWORD=admin123
  volumes:
  - mysql:/var/lib/mysql
  - mysql_config:/etc/mysql
 redis:
  image: "redis:alpine" 

volumes:
  mysql:
  mysql_config:
