piVersion: apps/v1
kind: StatefulSet
metadata:
  name: flaskapi-deployment
  labels:
    app: flaskapi-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskapi-1
  serviceName: flask-statefulset-frontend
  template:
    metadata:
      labels:
        app: flaskapi-1
    spec:
      initContainers:
        - name: init-db
          image: busybox:1.31
          command: ['sh', '-c', 'echo -e "MYSQL Server has started";']

      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
              name: redis
              protocol: TCP
        - name: flaskapi-container
          image: klogambigai/pythonweb:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: "REDIS_HOST"
              value: "localhost"
            - name: DB_HOSTNAME
              value: "mysql"
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: "guestapp"
            - name: DB_USERNAME
              value: "root"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-db
                  key: password
          #volumeMounts:
          #  - name: py-persistent-storage
          #    mountPath: /var/lib/mysql

